### PR TITLE
[CraftToStack] Add compatibility for EAQS and Epic Loot.

### PR DESCRIPTION
**Pull request by jsza**
Hi, just some additions to get things working with the above addons. This has no patches for Extended Item Data Framework as that is now compatible as-is in its latest update (1.0.1).

### CODE REVIEW

**Review by di98feja — APPROVED** [review]
Awesome, thank you for this!
If I understand correctly the compatpatches makes sure the transpiler patches is run first?

**Comment by jsza** [comment]
Most welcome! The DoCrafting patches in Epic Loot and EAQS override the original method call, and because they have almost the same code as in the base game, we can happily apply your existing DoCrafting transpiler to fix them in the same way.

**Comment by di98feja** [comment]
I've tested this with EquipmentAndQuickSlots and it does allow for crafting into a stack but it consumes the resources twice..
For example crafting 20 wooden arrows consume 16 wood instead of 8.
Then I tested with EpicLoot and since it requires ExtendedItemDataFramework it does not work either since EIDF seems to block CraftToStack.
So, sorry but this require some work still.

**Comment by jsza** [comment]
Oof, yeah sorry about that... I think I was testing with resource costs disabled. I'll push a fix for this soon.

I can't reproduce EIDF blocking CraftToStack; are you perhaps on an older version than 1.0.1?

**Comment by jsza** [comment]
https://github.com/jsza/RagnarsRokare/commit/3537ddee2ba816509e70f99544bf806a9b16e826 this fixes the double resource usage but item stacks now get stuck at 0 on the quick slot bar without being removed. Not sure what's going on, I'll come back to this tomorrow.

**Comment by jsza** [comment]
Not at my computer, so for future reference:

I think it might work to patch EAQS’s RemoveItem Prefix to sort inventories by minimum stack amount and then not run CraftToStack’s RemoveItem prefix when EAQS is doing an extended inventory call.

Might need to add EAQS as a reference if that’s the approach; would that be alright?

**Comment by di98feja** [comment]
You are right, the EIDF doesn't block CraftToStack anymore, not sure what fixed it though, I don't see any changes that should affect  that.. On the other hand I never understod what caused it either..  :P
When it comes to EAQS it does feel a bit wonky to patch another mods patches so i would rather just skip the RemoveItem patch in CraftToStack whenever EAQS is loaded and make a PR to implement the sorting in EAQS.

**Comment by jsza** [comment]
I think it was this change in EIDF’s AddItem patch (it was changed a while back and unreleased until a few days ago) to call CanAddItem instead of FindEmptySlot: https://github.com/RandyKnapp/ValheimMods/commit/1f113cfcca3fd40a0f0a8a463eae0b8f4a288d53#diff-81e2f877991db1ba85556c4004d197a88a416551e7dd036cb0afe9cbe2861ed5R72

**Comment by di98feja** [comment]
Ahh, that explains it..  I was looking at his code thinking that it SHOULD work, not realising it was unreleased.

**Comment by jsza** [comment]
I've tried a new approach applying CraftToStack's RemoveItem patch to OverrideRemoveItem in EAQS and it seems to work well: https://github.com/jsza/RagnarsRokare/commit/a6853486eab05c6560719e980540275b4effa0e8

If you're open to it shall I make a new PR?

**Comment by di98feja** [comment]
Alright, but I'm not thrilled to add connections to other mods like this since it makes my code more brittle.
Hopyfully Irongate fixes these bugs in the game code so I can ditch this mod completely.

**Comment by jsza** [comment]
Thanks, and yeah that's fair enough. For what it's worth I've added some more checks to bail out if it can't fetch the types from EAQS + Epic Loot, and it's fetching the types dynamically at runtime to avoid having either mod as a dependency. I'm also following EAQS closely so I'll keep an eye on compatibility stuff.

Sorry if I was pushing this too hard; our group's been itching to use this mod along with EAQS so I've been motivated 😛 

Thanks a ton for all your work on this :)

**Pull request merged**
